[application]

# App (Project) Name
name = "stats-dash"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Slippi Stats Dash"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["./src", "./assets"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["./dist/pico-1.5.9/css/pico.min.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
style = ["./dist/pico-1.5.9/css/pico.min.css"]

[bundle]
resources = ["./dist/pico-1.5.9"]